language: node_js

node_js:
  - "0.10"

jdk:
  - oraclejdk7  # needed for local Neo4j 2.0+

env:
  - NEO4J_VERSION="2.2.2"

before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start

# this *does* CI pull requests to master:
branches:
  only:
    - master
